<h1>Задания</h1>

<h5>1. Использование команд библиотеки NumPy</h5>
<ul>
    <li><b>1.1.</b> Создайте одномерный массив <i>my_array</i>, в котором по порядку все числа до 100, кратные 5</li>
    <li><b>2.1.</b> Из полученного массива получить массив с кратными 10 числами</li>
    <li><b>3.1.</b> Получить двумерный массив с двумя столбцами</li>
    <li><b>4.1.</b> Получите набор <i>my_second_array</i>, в котором все элементы меньше предыдущего исходного на 5</li>
    <li><b>5.1.</b> Соедините массивы, полученные в п. 3.1 и 4.1, горизонтально. Используйте <i>.T</i> для транспонирования матрицы.</li>
    <li><b>6.1.</b> Разделите 2 и 3 строку на 4 верхних строки <i>my_array</i>. Используйте <i>.T</i> для транспонирования матрицы</li>
    <li><b>7.1.</b> Оставить только те значения, которые не изменились после деления</li>
    <li><b>8.1.</b> Снова получить трехстрочный двумерный массив и поменять местами первую и третью строки</li>
    <li><b>9.1.</b> Получить среднее, медиану и стандартное отклонение для каждой строки, используя команды <i>np.mean()</i>, <i>np.median()</i>, <i>np.std()</i>.</li>
    <li><b>10.1.</b> Сделать нормализацию на максимальное значение вдоль строк, поделив каждый элемент массива на <i>max()</i> вдоль строк.</li>
</ul>


In [18]:
import numpy as np

# 1.1 Создание одномерного массива чисел от 5 до 100 с шагом 5
my_array = np.arange(5, 100, 5)

# Обрезаем массив до 18 элементов, чтобы общее количество делилось на 2
my_array_trimmed = my_array[:18]

# 2.1 Извлечение чисел, кратных 10
multiples_of_10 = my_array_trimmed[my_array_trimmed % 10 == 0]

# 3.1 Преобразование одномерного массива в двумерный с двумя столбцами
two_column_array = my_array_trimmed.reshape(-1, 2)

# 4.1 Создание нового массива, где каждый элемент уменьшен на 5
my_second_array = my_array_trimmed - 5

# Преобразование второго массива в двумерный для совместимости по размерам
my_second_array_reshaped = my_second_array.reshape(-1, 2)

# 5.1 Объединение двух массивов и транспонирование результата
combined_array = np.hstack((two_column_array, my_second_array_reshaped)).T

# 6.1 Поэлементное деление 2-й и 3-й строки на 1-ю и 2-ю строки соответственно
div_result = combined_array[1:3] / combined_array[0:2]

# 7.1 Извлечение значений, которые не изменились после деления
unchanged_values = div_result[div_result == 1]

# 8.1 Перестановка строк в массиве: меняем местами 1-ю и 3-ю строки
three_row_array = combined_array[:3]
three_row_array[[0, 2]] = three_row_array[[2, 0]]

# 9.1 Вычисление среднего, медианы и стандартного отклонения для каждой строки
mean_values = np.mean(three_row_array, axis=1)
median_values = np.median(three_row_array, axis=1)
std_values = np.std(three_row_array, axis=1)

# 10.1 Нормализация каждой строки на максимальное значение в строке
normalized_array = three_row_array / np.max(three_row_array, axis=1, keepdims=True)

# Вывод результатов
print("Исходный массив:", my_array_trimmed)
print("Числа, кратные 10:", multiples_of_10)
print("Двумерный массив с двумя столбцами:", two_column_array)
print("Объединенный и транспонированный массив:", combined_array)
print("Результат поэлементного деления:", div_result)
print("Значения, которые не изменились после деления:", unchanged_values)
print("Массив после перестановки строк:", three_row_array)
print("Средние значения:", mean_values)
print("Медианы:", median_values)
print("Стандартные отклонения:", std_values)
print("Нормализованный массив:", normalized_array)


Исходный массив: [ 5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90]
Числа, кратные 10: [10 20 30 40 50 60 70 80 90]
Двумерный массив с двумя столбцами: [[ 5 10]
 [15 20]
 [25 30]
 [35 40]
 [45 50]
 [55 60]
 [65 70]
 [75 80]
 [85 90]]
Объединенный и транспонированный массив: [[ 0 10 20 30 40 50 60 70 80]
 [10 20 30 40 50 60 70 80 90]
 [ 5 15 25 35 45 55 65 75 85]
 [ 5 15 25 35 45 55 65 75 85]]
Результат поэлементного деления: [[2.         1.33333333 1.2        1.14285714 1.11111111 1.09090909
  1.07692308 1.06666667 1.05882353]
 [0.         0.5        0.66666667 0.75       0.8        0.83333333
  0.85714286 0.875      0.88888889]]
Значения, которые не изменились после деления: []
Массив после перестановки строк: [[ 0 10 20 30 40 50 60 70 80]
 [10 20 30 40 50 60 70 80 90]
 [ 5 15 25 35 45 55 65 75 85]]
Средние значения: [40. 50. 45.]
Медианы: [40. 50. 45.]
Стандартные отклонения: [25.81988897 25.81988897 25.81988897]
Нормализованный массив: [[0.         0.125      0.25       0.375  

<h5>2. Использование команд библиотеки pandas</h5>
<ul>
    <li>Подключите библиотеку pandas</li>
    <li><b>2.1.</b> Импортируйте данные из файла “Global Population Trends(2016-2022).csv”. Описание данных смотрите ниже.</li>
    <li>Изучите полученные данные:</li>
    <li><b>2.2.</b> Считайте несколько первых записей таблицы (head())</li>
    <li><b>2.3.</b> Определите размерность данного фрейма (shape())</li>
    <li><b>2.4.</b> Выведите название заголовков столбцов фрейма (columns)</li>
    <li><b>2.5.</b> Получите описание всех переменных (полей) (info())</li>
    <li><b>2.6.</b> Удалите строки, не содержащие значения в столбце «Total Population» - “-”<br>
        </li>
    <li><b>2.7.</b> Получите описательную статистику по переменным (например, max(), min(), describe())</li>
    <li><b>2.8.</b> Выполните сортировку данных по нескольким критериям</li>
    <li><b>2.9.</b> Выведите название страны, которая имеет максимальную численность населения</li>
    <li><b>2.10.</b> Выведите название страны, которая имеет минимальную численность населения</li>
    <li><b>2.11.</b> Экспорт фрейма в MS Excel</li>
</ul>



In [19]:

import pandas as pd

# 2.1 Импорт данных из CSV файла
df = pd.read_csv(r"Global Population Trends(2016-2022).csv")

# 2.2 Вывод первых нескольких записей таблицы
print("Первые несколько записей:")
print(df.head())

# 2.3 Определение размерности фрейма
print("Размерность фрейма:", df.shape)

# 2.4 Вывод названий столбцов
print("Названия заголовков столбцов:", df.columns)

# 2.5 Вывод информации о данных
print("Описание данных:")
print(df.info())

# 2.6 Удаление строк, где в столбце «Total Population» содержится символ "-"
df1 = df[df['Total Population'] != '-']

# Удаление запятых и преобразование столбца «Total Population» в числовой формат
df1.loc[:, 'Total Population'] = df1['Total Population'].str.replace(',', '').astype(float)

# 2.7 Описательная статистика по переменным
print("Описательная статистика:")
print(df1.describe())

# 2.8 Сортировка данных по «Total Population» и «Country»
df1_sorted = df1.sort_values(by=['Total Population', 'Country'], ascending=[False, True])
print("Отсортированные данные:")
print(df1_sorted.head())

# 2.9 Определение страны с максимальной численностью населения
max_population_country = df1.loc[df1['Total Population'].idxmax(), 'Country']
print("Страна с максимальной численностью населения:", max_population_country)

# 2.10 Определение страны с минимальной численностью населения
min_population_country = df1.loc[df1['Total Population'].idxmin(), 'Country']
print("Страна с минимальной численностью населения:", min_population_country)

# Убедитесь, что модуль openpyxl установлен для экспорта в Excel
# Если не установлен, выполните: pip install openpyxl

# 2.11 Экспорт данных в Excel файл
df1.to_excel("Global_Population_Trends_Exported.xlsx", index=False, engine='openpyxl')


Первые несколько записей:
       Country  Year Total Population Urban Population Rural Population  \
0  Afghanistan  2017                -                -                -   
1  Afghanistan  2018       36,686,784        9,353,296       27,333,488   
2  Afghanistan  2019       37,769,499        9,727,157       28,042,342   
3  Afghanistan  2020       38,972,230       10,142,913       28,829,317   
4  Afghanistan  2021       40,099,462       10,551,772       29,547,690   

  Population Density Life Expectancy  Birth Rate  Death Rate Fertility Rate  \
0                 55            63.0      37.342       7.027          5.129   
1                 56            63.0      36.927       6.981          5.002   
2                 58            64.0      36.466       6.791           4.87   
3                 60            63.0      36.051       7.113           4.75   
4                  -            62.0      35.842       7.344          4.643   

  Infant Mortality Rate Growth Rate  
0         